# permissions for end users to view koupletbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: koupletbuild-viewer-role
rules:
- apiGroups:
  - api.kouplet.com
  resources:
  - koupletbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.kouplet.com
  resources:
  - koupletbuilds/status
  verbs:
  - get
