# permissions for end users to edit koupletbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: koupletbuild-editor-role
rules:
- apiGroups:
  - api.kouplet.com
  resources:
  - koupletbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.kouplet.com
  resources:
  - koupletbuilds/status
  verbs:
  - get
