# permissions for end users to edit kouplettests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kouplettest-editor-role
rules:
- apiGroups:
  - api.kouplet.com
  resources:
  - kouplettests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.kouplet.com
  resources:
  - kouplettests/status
  verbs:
  - get
