# permissions for end users to view kouplettests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kouplettest-viewer-role
rules:
- apiGroups:
  - api.kouplet.com
  resources:
  - kouplettests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.kouplet.com
  resources:
  - kouplettests/status
  verbs:
  - get
