
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.kouplet.com
  resources:
  - koupletbuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.kouplet.com
  resources:
  - koupletbuilds/finalizers
  verbs:
  - update
- apiGroups:
  - api.kouplet.com
  resources:
  - koupletbuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - api.kouplet.com
  resources:
  - kouplettests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.kouplet.com
  resources:
  - kouplettests/finalizers
  verbs:
  - update
- apiGroups:
  - api.kouplet.com
  resources:
  - kouplettests/status
  verbs:
  - get
  - patch
  - update
