kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kouplet
subjects:
- kind: ServiceAccount
  name: kouplet
roleRef:
  kind: Role
  name: kouplet
  apiGroup: rbac.authorization.k8s.io
